 
services:
    php:
        build:
            context: ./config/php
        ports:
            - 9000:9000
        volumes:
            - ./web:/srv/www/api
            - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: example
            MYSQL_PASSWORD: secret2
        depends_on:
            - db
        links:
            - db
 
    nginx:
        image: nginx:1.17
        ports:
            - 80:80
        volumes:
            - ./web:/srv/www/api
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            
    db:
        image: mysql:latest
        ports:
            - ${IP}:3300:3306
        command: "mysqld --init-file /data/application/init.sql"
        volumes:
            - ./data/init.sql:/data/application/init.sql
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: stage   
            MYSQL_USER: example
            MYSQL_PASSWORD: secret2
volumes:
    db_data:
